# Generated by Django 4.0.2 on 2022-02-16 18:28

from django.db import migrations, models
import sequence.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_code', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA'), ('AMINO-ACID', 'Amino-acid')], default='DNA', max_length=10)),
                ('type_of_sequence', models.CharField(choices=[('REFERENCE', 'REFERENCE'), ('READ', 'READ')], default='READ', max_length=11)),
                ('sequence_name', models.CharField(max_length=20)),
                ('sequence', models.TextField(max_length=1000)),
                ('publication_date', models.DateTimeField(verbose_name='date published')),
                ('coding_regions', models.JSONField(default=sequence.models.json_default_value)),
                ('start_offset', models.IntegerField(verbose_name='Sequence offset from the reference')),
            ],
        ),
    ]
