# Generated by Django 4.0.2 on 2022-03-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='id',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
