# Generated by Django 4.0.2 on 2022-03-04 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0002_remove_sequence_id_alter_sequence_sequence_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('alignment_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='alignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sequence.alignment'),
        ),
    ]
