# Generated by Django 4.0.2 on 2022-03-10 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0003_alignment_sequence_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alignment',
            name='object_creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 15, 56, 3, 907799), verbose_name='Key as date-time field'),
        ),
    ]
