# Generated by Django 4.0.2 on 2022-03-10 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sequence', '0005_alter_alignment_object_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alignment',
            name='object_creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Key as date-time field'),
        ),
    ]
